# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.botastic_smartmeter: debug

ffmpeg:
  ffmpeg_bin: /bin/true

# Enable VSCode debugging
# debugpy:
#   start: true
#   wait: true